### ISSUE TITLE
论文中的方法

### ISSUE THREAD

**Issue by Dandelion111** [yuliu316316/MFIF#1]
刘老师您好，是否可以提供一下这篇论文中所用到的图像融合方法，用来做对比试验

**Comment by yuliu316316** [comment]
您好！论文里给了相关方法的代码链接。


祝好！
刘羽





发件人：Dandelion111 <notifications@github.com>
发送日期：2020-11-16 16:07:33
收件人：yuliu316316/MFIF <MFIF@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[yuliu316316/MFIF] 论文中的方法 (#1)

刘老师您好，是否可以提供一下这篇论文中所用到的图像融合方法，用来做对比试验

**Comment by Dandelion111** [comment]
看到了，谢谢刘老师！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuliu316316/MFIF"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 晚上8:08
收件人:&nbsp;"yuliu316316/MFIF"<MFIF@noreply.github.com&gt;;
抄送:&nbsp;"刷新丶"<zhaochengsh@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuliu316316/MFIF] 论文中的方法 (#1)





 
 您好！论文里给了相关方法的代码链接。
 
 
 祝好！
 刘羽
 
 
 
 
 
 发件人：Dandelion111 <notifications@github.com&gt;
 发送日期：2020-11-16 16:07:33
 收件人：yuliu316316/MFIF <MFIF@noreply.github.com&gt;
 抄送人：Subscribed <subscribed@noreply.github.com&gt;
 主题：[yuliu316316/MFIF] 论文中的方法 (#1)
 
 刘老师您好，是否可以提供一下这篇论文中所用到的图像融合方法，用来做对比试验
